In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [6]:
df = pd.read_csv('apple_products.csv')
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         62 non-null     object
 1   Product URL          62 non-null     object
 2   Brand                62 non-null     object
 3   Sale Price           62 non-null     int64
 4   Mrp                  62 non-null     int64
 5   Discount Percentage  62 non-null     int64
 6   Number Of Ratings    62 non-null     int64
 7   Number Of Reviews    62 non-null     int64
 8   Upc                  62 non-null     object
 9   Star Rating          62 non-null     float64
 10  Ram                  62 non-null     object
dtypes: float64(1), int64(5), object(5)
memory usage: 5.5+ KB

In [8]:
df.isnull().sum()

Product Name           0
Product URL            0
Brand                  0
Sale Price             0
Mrp                    0
Discount Percentage    0
Number Of Ratings      0
Number Of Reviews      0
Upc                    0
Star Rating            0
Ram                    0
dtype: int64

#### It does not have any Missing values

In [9]:
df.describe()

,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating
count,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000
mean,80073.887097,88058.064516,9.951613,22420.403226,1861.677419,4.575806
std,34310.446132,34728.825597,7.608079,33768.589550,2855.883830,0.059190
min,29999.000000,39900.000000,0.000000,542.000000,42.000000,4.500000
25%,49900.000000,54900.000000,6.000000,740.000000,64.000000,4.500000
50%,75900.000000,79900.000000,10.000000,2101.000000,180.000000,4.600000
75%,117100.000000,120950.000000,14.000000,43470.000000,3331.000000,4.600000
max,140900.000000,149900.000000,29.000000,95909.000000,8161.000000,4.700000

In [11]:
df.columns

Index(['Product Name', 'Product URL', 'Brand', 'Sale Price', 'Mrp',
       'Discount Percentage', 'Number Of Ratings', 'Number Of Reviews', 'Upc',
       'Star Rating', 'Ram'],
      dtype='object')

In [20]:
# top 10 highest-rated iphones on flipkart in india
highest_rated = df.sort_values(by='Star Rating', ascending=False)
highest_rated = highest_rated.head(10)
highest_rated[['Product Name', 'Star Rating']]

                                         Product Name  Star Rating
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)          4.7
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)          4.7
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)          4.7
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)          4.7
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)          4.7
0                   APPLE iPhone 8 Plus (Gold, 64 GB)          4.6
12  Apple iPhone XR (Black, 128 GB) (Includes EarP...          4.6
11  Apple iPhone XR (Coral, 128 GB) (Includes EarP...          4.6
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...          4.6
1            APPLE iPhone 8 Plus (Space Grey, 256 GB)          4.6

In [18]:
print(highest_rated['Product Name'])

15                APPLE iPhone 11 Pro Max (Gold, 64 GB)
20      APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)
17          APPLE iPhone 11 Pro Max (Space Grey, 64 GB)
16     APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)
14               APPLE iPhone 11 Pro Max (Gold, 256 GB)
0                     APPLE iPhone 8 Plus (Gold, 64 GB)
12    Apple iPhone XR (Black, 128 GB) (Includes EarP...
11    Apple iPhone XR (Coral, 128 GB) (Includes EarP...
9     Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...
1              APPLE iPhone 8 Plus (Space Grey, 256 GB)
Name: Product Name, dtype: object

In [21]:
print(highest_rated)

                                         Product Name  \
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)
0                   APPLE iPhone 8 Plus (Gold, 64 GB)
12  Apple iPhone XR (Black, 128 GB) (Includes EarP...
11  Apple iPhone XR (Coral, 128 GB) (Includes EarP...
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...
1            APPLE iPhone 8 Plus (Space Grey, 256 GB)

                                          Product URL  Brand  Sale Price  \
15  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      117100
20  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      117100
17  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      117100
16  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      131900
14  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      131900
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple       49900
12  https://www.flipkart.com/apple-iphone-xr-black...  Apple       41999
11  https://www.flipkart.com/apple-iphone-xr-coral...  Apple       41999
9   https://www.flipkart.com/apple-iphone-xr-produ...  Apple       41999
1   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900

       Mrp  Discount Percentage  Number Of Ratings  Number Of Reviews  \
15  117100                    0               1078                101
20  117100                    0               1078                101
17  117100                    0               1078                101
16  131900                    0               1078                101
14  131900                    0               1078                101
0    49900                    0               3431                356
12   52900                   20              79512               6796
11   52900                   20              79582               6804
9    52900                   20              79512               6796
1    84900                    0               3431                356

                 Upc  Star Rating   Ram
15  MOBFKCTSAPAYNSGG          4.7  4 GB
20  MOBFKCTSRYPAQNYT          4.7  4 GB
17  MOBFKCTSKDMKCGQS          4.7  4 GB
16  MOBFKCTSCAAKGQV7          4.7  4 GB
14  MOBFKCTS7HCHSPFH          4.7  4 GB
0   MOBEXRGV7EHHTGUH          4.6  2 GB
12  MOBF9Z7ZYWNFGZUC          4.6  3 GB
11  MOBF9Z7ZS6GF5UAP          4.6  4 GB
9   MOBF9Z7ZHQC23PWQ          4.6  4 GB
1   MOBEXRGVAC6TJT4F          4.6  2 GB

In [23]:
# How many ratings do the highest-rated iphones have?


df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [ ]:
labels = highest_rated['Product Name']
counts = highest_rated['Number Of Ratings']
figure = px.bar(highest_rated, x=labels, y=counts, title='Number of Ratings for Highest-Rated iPhones')
figure.update_layout(xaxis_title='Product Name', yaxis_title='Number Of Ratings')
figure.show()

KeyError: 'Number of Ratings'