In [20]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,cross_val_score,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.svm import SVC
import joblib

In [2]:
df = pd.read_csv('loan_data.csv')
df.head()

    Loan_ID Gender Married  ... Credit_History Property_Area Loan_Status
0  LP001003   Male     Yes  ...            1.0         Rural           N
1  LP001005   Male     Yes  ...            1.0         Urban           Y
2  LP001006   Male     Yes  ...            1.0         Urban           Y
3  LP001008   Male      No  ...            1.0         Urban           Y
4  LP001013   Male     Yes  ...            1.0         Urban           Y

[5 rows x 13 columns]

In [3]:
df.shape

(381, 13)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            381 non-null    object
 1   Gender             376 non-null    object
 2   Married            381 non-null    object
 3   Dependents         373 non-null    object
 4   Education          381 non-null    object
 5   Self_Employed      360 non-null    object
 6   ApplicantIncome    381 non-null    int64
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    float64
 9   Loan_Amount_Term   370 non-null    float64
 10  Credit_History     351 non-null    float64
 11  Property_Area      381 non-null    object
 12  Loan_Status        381 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 38.8+ KB

In [5]:
df = df.drop(['Loan_ID'],axis=1)

In [6]:
df.isnull().mean()*100

Gender               1.312336
Married              0.000000
Dependents           2.099738
Education            0.000000
Self_Employed        5.511811
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     2.887139
Credit_History       7.874016
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [7]:
df = df.dropna(subset=['Gender','Dependents','Loan_Amount_Term'])
df.shape

(358, 12)

In [8]:
df.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed        20
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [9]:
df['Self_Employed'].unique()

array(['No', 'Yes', nan], dtype=object)

In [10]:
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0],inplace=True)
df['Credit_History'].fillna(df['Credit_History'].mode()[0],inplace=True)
df.isnull().sum()

C:\Users\MY PC\AppData\Local\Temp\ipykernel_3148\3473918315.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Credit_History'].fillna(df['Credit_History'].mode()[0],inplace=True)

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 358 entries, 0 to 380
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             358 non-null    object
 1   Married            358 non-null    object
 2   Dependents         358 non-null    object
 3   Education          358 non-null    object
 4   Self_Employed      358 non-null    object
 5   ApplicantIncome    358 non-null    int64
 6   CoapplicantIncome  358 non-null    float64
 7   LoanAmount         358 non-null    float64
 8   Loan_Amount_Term   358 non-null    float64
 9   Credit_History     358 non-null    float64
 10  Property_Area      358 non-null    object
 11  Loan_Status        358 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 36.4+ KB

In [12]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [13]:
df['Dependents'].unique()

array(['1', '0', '2', '3+'], dtype=object)

In [14]:
df['Dependents'].value_counts()

Dependents
0     223
2      57
1      51
3+     27
Name: count, dtype: int64

In [15]:
df['Dependents'].replace('3+','4',inplace=True)

In [ ]:

df['Married'].value_counts()

Married
Yes    216
No     142
Name: count, dtype: int64

In [18]:
encoding = {
    'Gender':{
        'Male':1,
        'Female':0
    },
    'Married':{
        'Yes':1,
        'No':0
    },
    'Dependents':{
        '0':0,
        '1':1,
        '2':2,
        '4':4
    },
    'Education':{
        'Graduate':1,
        'Not Graduate':0
    },
    'Self_Employed':{
        'No':0,
        'Yes':1
    },
    'Property_Area' :{
        'Rural':0,
        'Semiurban':1,
        'Urban':2
    },
    'Loan_Status':{
        'N':0,
        'Y':1
    }




}
df.replace(encoding, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 358 entries, 0 to 380
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             358 non-null    int64
 1   Married            358 non-null    int64
 2   Dependents         358 non-null    int64
 3   Education          358 non-null    int64
 4   Self_Employed      358 non-null    int64
 5   ApplicantIncome    358 non-null    int64
 6   CoapplicantIncome  358 non-null    float64
 7   LoanAmount         358 non-null    float64
 8   Loan_Amount_Term   358 non-null    float64
 9   Credit_History     358 non-null    float64
 10  Property_Area      358 non-null    int64
 11  Loan_Status        358 non-null    int64
dtypes: float64(4), int64(8)
memory usage: 36.4 KB

C:\Users\MY PC\AppData\Local\Temp\ipykernel_3148\2128347871.py:38: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(encoding, inplace=True)

In [19]:
X = df.drop('Loan_Status',axis=1)
y = df['Loan_Status']

num_cols = ['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']
scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])
X.head()

   Gender  Married  Dependents  ...  Loan_Amount_Term  Credit_History  Property_Area
0       1        1           1  ...          0.285826             1.0              0
1       1        1           0  ...          0.285826             1.0              2
2       1        1           0  ...          0.285826             1.0              2
3       1        0           0  ...          0.285826             1.0              2
4       1        1           0  ...          0.285826             1.0              2

[5 rows x 11 columns]

In [24]:
def evaluate_model(model):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    cross_val = cross_val_score(model, X, y, cv=5).mean()
    avg_cross_val = np.mean(cross_val)
    print(f"{model.__class__.__name__} - Accuracy: {accuracy:.2f}, Cross-Validation: {avg_cross_val:.2f}")
    return avg_cross_val

In [22]:
models = {
    'Logistic Regression':LogisticRegression(),
    'Decision Tree':DecisionTreeClassifier(),
    'Random Forest':RandomForestClassifier(),
    'Gradient Boosting':GradientBoostingClassifier()
}

In [ ]:
={model.__class__.__name__:evaluate_model(model) for model in models}